dist: trusty
#sudo: required
notifications:
email: false
language: java
#addons:
#  apt:
#    packages:
jdk:
- oraclejdk8
#before_install:
#- sudo add-apt-repository ppa:dns/gnu -y
#- sudo apt-get update -qq
#install:
#- sudo apt-get install -y --force-yes autoconf dos2unix icoutils xsltproc genisoimage
script:
- common/scripts/build-harctoolbox-project.sh IrpTransmogrifier
#- tools/build-harctoolbox-project.sh Girr
#- tools/build-harctoolbox-project.sh Jirc
#- tools/build-harctoolbox-project.sh DevSlashLirc
#- tools/build-harctoolbox-project.sh RXTX
#- tools/build-harctoolbox-project.sh HarcHardware
#- tools/build-tonto.sh -n
#- tools/get-jdk.sh linux
#- wget --quiet http://www.harctoolbox.org/downloads/jre-x64-macOS.tar.gz
#- tools/get-inno.sh
- mvn install -DskipTests=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V
- ls -l --si target
- common/scripts/upload.sh target/*-bin.zip target/*.md5 target/*.sha*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:ci-build)$/
