dist: trusty
notifications:
email: false
language: java
jdk: oraclejdk8
install: ./common/scripts/build-harctoolbox-project.sh IrpTransmogrifier
after_success: ./common/scripts/upload.sh target/*-bin.zip target/*.md5 target/*.sha*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:ci-build)$/
